### ISSUE TITLE
Settings sections change startup to be map specific

### ISSUE THREAD

**Issue by OvermindDL1** [abaines/Companionship#4]
Currently there are two startup options and one runtime-per-user option.  Any chance of the two startup options changing to become map specific options?  I'd like to have different values on different maps (and it would be convenient to change them on the fly as situations change and more people end up wanting to permanently join overtime).

**Comment by abaines** [comment]
For my desired use case, I like those settings as is.  Feel free to fork the mod/repo and change those values if you wish.  Unfortunately, I probably won't changing it anytime soon. ☹

Thank you for the feedback.  🙏
